{{- /* Name of this template, used to access its config in .Values */}}
{{- $templateName := "k8sblockloadbalancer" }}
{{- $templateConfig := index .Values.constraintTemplates $templateName }}

{{- /* Only render if enabled in .Values */}}
{{- if $templateConfig.enabled }}
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: {{ $templateName }}
  labels:
    {{- include "gatekeeper.commonLabels" . | nindent 4 }}
  annotations:
    metadata.gatekeeper.sh/title: "Block LoadBalancer Services (Simplified Test)"
    metadata.gatekeeper.sh/version: "0.0.1-test"
    description: "Test: Disallows Kubernetes Services of type LoadBalancer."
spec:
  crd:
    spec:
      names:
        kind: K8sBlockLoadBalancer # Still using the same Kind name
      validation:
        legacySchema: false
        openAPIV3Schema:
          type: object # Simplest possible schema - no parameters
          description: "Test schema, no parameters."
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblockloadbalancertest # Changed package name slightly for clarity if needed

        violation[{"msg": msg}] {
          input.review.kind.kind == "Service"
          input.review.object.spec.type == "LoadBalancer"
          msg := "TEST: Services of type LoadBalancer are not allowed."
        }
{{- end }}
