{{- /* Name of the ConstraintTemplate this Constraint is based on */}}
{{- $templateName := "k8sblockwildcardingress" }}
{{- /* Get the configuration for this specific template from .Values */}}
{{- $templateConfig := index .Values.constraintTemplates $templateName }}

{{- /* Only render if enabled in .Values. */}}
{{- if $templateConfig.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockWildcardIngress {{/* Must match spec.crd.spec.names.kind from the ConstraintTemplate */}}
metadata:
  name: {{ $templateName }}-enforce {{/* Name of this specific constraint instance */}}
  labels:
    {{- include "gatekeeper.commonLabels" . | nindent 4 }}
spec:
  enforcementAction: {{ $templateConfig.enforcementAction | default "dryrun" }} # Default to dryrun
  match:
    {{- /* Default match targets Ingress resources. User can override via values.yaml */}}
    {{- $defaultMatch := dict "kinds" (list (dict "apiGroups" (list "networking.k8s.io") "kinds" (list "Ingress"))) }}
    {{- toYaml ($templateConfig.match | default $defaultMatch) | nindent 4 }}
  parameters:
    {{- /* Pass params if they exist in values.yaml ($templateConfig.params).
         If $templateConfig.params is nil or empty, pass an empty YAML map '{}'.
         The Rego in the ConstraintTemplate handles the case where 'message' is not provided. */}}
    {{- if $templateConfig.params }}
    {{- toYaml $templateConfig.params | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
{{- end }}
