{{- $constraintName := "k8spspallowedusers-enforce" }}
{{- $templateName := "k8spspallowedusers" }}
{{- $templateConfig := index .Values.constraintTemplates $templateName }}

{{- if $templateConfig.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers # Must match spec.crd.spec.names.kind from the ConstraintTemplate
metadata:
  name: {{ $constraintName }}
  namespace: {{ .Release.Namespace | default "opa-test" }} # Use Release.Namespace or a sensible default
  labels:
    {{- include "gatekeeper.commonLabels" . | nindent 4 }}
  annotations:

spec:
  enforcementAction: {{ $templateConfig.enforcementAction | default "dryrun" }} # Default to dryrun
  match:
    {{- /* Default match targets Pods, as this policy relates to Pod Security. User can override. */}}
    {{- $defaultMatch := dict "kinds" (list (dict "apiGroups" (list "") "kinds" (list "Pod"))) }}
    {{- toYaml ($templateConfig.match | default $defaultMatch) | nindent 4 }}
  parameters:
    {{- /* Pass all params. The openAPIV3Schema in the ConstraintTemplate defines the expected structure. */}}
    {{- if $templateConfig.params }}
    {{- toYaml $templateConfig.params | nindent 4 }}
    {{- else }}
    {} # Pass an empty object if no params are defined in values.yaml for this constraint.
    {{- end }}
{{- end }}
