# filename: enforce-unique-service-selector.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sUniqueServiceSelector # Must exactly match the 'kind' in the ConstraintTemplate
metadata:
  name: enforce-unique-service-selectors # A unique name for this constraint instance
spec:
  # Enforcement action:
  # "deny" (default): Blocks resource creation/update if violated.
  # "dryrun": Reports violations without blocking.
  # "warn": Reports violations as a warning.
  enforcementAction: dryrun 
  match:
    kinds:
      - apiGroups: [""] # Target core Kubernetes API group
        kinds: ["Service"] # Target Service resources
    # To restrict to specific namespaces, uncomment and list them:
    # namespaces:
    #   - default
    #   - my-app-namespace
  # No parameters are defined for this ConstraintTemplate, so parameters block is empty.
  parameters: {}
