{{- $templateName := "k8suniqueserviceselector" }}
{{- $templateConfig := index .Values.constraintTemplates $templateName }}

{{- if $templateConfig.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8suniqueserviceselector {{/* Must match spec.crd.spec.names.kind from the ConstraintTemplate */}}
metadata:
  name: {{ $templateName }}-enforce {{/* Name of this specific constraint instance */}}
  labels:
    {{- include "gatekeeper.commonLabels" . | nindent 4 }}
spec:
  enforcementAction: {{ $templateConfig.enforcementAction | default "dryrun" }} # Default to dryrun
  match:
    {{- /* This policy specifically targets Service resources. */}}
    {{- $defaultMatch := dict "kinds" (list (dict "apiGroups" (list "") "versions" (list "v1") "kinds" (list "Service"))) }}
    {{- toYaml ($templateConfig.match | default $defaultMatch) | nindent 4 }}
  # This ConstraintTemplate defines no configurable parameters.
  # Gatekeeper requires the 'parameters' field if the schema type is 'object'.
  parameters: {}
{{- end }}
