apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-policy-manager
spec:
  type: NodePort
  selector:
    app: gatekeeper-policy-manager
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30484
