apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-policy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper-policy-manager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: gatekeeper-policy-manager
    spec:
      serviceAccountName: gatekeeper-policy-manager
      containers:
      - name: gatekeeper-policy-manager
        image: quay.io/sighup/gatekeeper-policy-manager
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: kubeguard
        operator: Exists
        effect: NoSchedule
